
spring:
  datasource:
    url: jdbc:mariadb://hellojhworld-database.c7xo15ztjyyx.ap-northeast-2.rds.amazonaws.com:3306/db_hellojhworld
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: jae156212!
#    url: jdbc:h2:tcp://localhost/~/hellojhworld
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: jae156

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug